eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8765
spring:
  application:
    name: service-zuul
zuul:
  prefix: /api
  routes:
    a:
      path: /a/**
      service-id: service-client
    b:
      path: /b/**
      service-id: service-client2
    c:
      path: /c/**
      service-id: service-ribbon